### ISSUE TITLE
Finish module models

### ISSUE THREAD

**Issue by GitChef** [Sproutwise/Magento2#1]
#### Overview

This is an automatically created issue through JIRA.

| Q               | A
| --------------- | -------------
| Magento version | -
| Module version  | 1.0.0
| Serverity       | Critical

#### Description

The module models (payment methods), store configuration and backend settings need to be finished.

**Comment by GitChef** [comment]
Changed issue status from `New` to `In Progress`.

**Comment by RicardoJ** [comment]
The optional configuration within the files will be done per issue and its scope.

**Comment by GitChef** [comment]
Changed issue status from `In Progress` to `Resolved`.
